apiVersion: apps/v1
kind: Deployment
metadata:
  name: mscv-service-name
  labels:
    app: mscv-service-name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mscv-service-name
  template:
    metadata:
      labels:
        app: mscv-service-name
    spec:
      containers:
      - name: mscv-service-name-service
        image: docker.io/library/mscv_service_test:20.04
        imagePullPolicy: Never
        envFrom:
          - configMapRef:
              name: mscv-envs-config
        ports:
        - containerPort: 50003
---
apiVersion: v1
kind: Service
metadata:
  name: mscv-service-name-svc
spec:
  selector:
    app: mscv-service-name
  type: ClusterIP
  ports:
    - protocol: TCP
      # internal service port
      port: 50003
      # cluster redirect port
      targetPort: 50003
