apiVersion: apps/v1
kind: Deployment
metadata:
  name: mscv-master
  labels:
    app: mscv-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mscv-master
  template:
    metadata:
      labels:
        app: mscv-master
    spec:
      containers:
      - name: mscv-master-container
        image: docker.io/library/mscv-master:0.1
        imagePullPolicy: Never
        envFrom:
          - configMapRef:
              name: mscv-envs-config
        ports:
        - containerPort: 50001
---
apiVersion: v1
kind: Service
metadata:
  name: mscv-master-svc
spec:
  selector:
    app: mscv-master
  type: NodePort
  ports:
    - protocol: TCP
      # cluster access port
      port: 50000
      # container service port
      targetPort: 50001
      # external access port
      nodePort: 50001
